---
dc_name: DC1_FABRIC

# Spine Switches
spine:
  defaults:
    platform: cEOS
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.255.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    evpn_route_servers: [ eos1 ]
    mlag_peer_ipv4_pool: 10.255.251.0/24
    mlag_peer_l3_ipv4_pool: 10.255.250.0/24
  nodes:
    eos2:
      id: 1
      mgmt_ip: 192.168.0.11/24
    eos5:
      id: 2
      mgmt_ip: 192.168.0.14/24

l3leaf:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    uplink_interfaces: [ Ethernet3, Ethernet4 ]
    uplink_switches: [ eos2, eos5 ]
    uplink_ipv4_pool: 172.31.255.0/24
    mlag_interfaces: [ Ethernet5 ]
    mlag_peer_ipv4_pool: 10.255.251.0/24
    mlag_peer_l3_ipv4_pool: 10.255.250.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    spanning_tree_mode: none
  node_groups:
    DC1_LEAF12:
      bgp_as: 65101
      nodes:
        eos3:
          id: 1
          mgmt_ip: 192.168.0.12/24
          # Interface configured on SPINES to connect to this leaf
          uplink_switch_interfaces: [ Ethernet1, Ethernet2 ]
        eos4:
          id: 2
          mgmt_ip: 192.168.0.13/24
          # Interface configured on SPINES to connect to this leaf
          uplink_switch_interfaces: [ Ethernet2, Ethernet1 ]
