---
dc_name: DC2_FABRIC

# Spine Switches
spine:
  defaults:
    platform: cEOS
    bgp_as: 65002
    loopback_ipv4_pool: 192.168.253.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    evpn_route_servers: [ eos2, eos5 ]
    mlag_peer_ipv4_pool: 10.255.251.0/24
    mlag_peer_l3_ipv4_pool: 10.255.250.0/24
  nodes:
    eos1:
      id: 1
      mgmt_ip: 192.168.0.10/24

l3leaf:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 192.168.253.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.252.0/24
    uplink_interfaces: [ Ethernet1 ]
    uplink_switches: [ eos1 ]
    uplink_ipv4_pool: 172.31.254.0/24
    mlag_interfaces: [ Ethernet3 ]
    mlag_peer_ipv4_pool: 10.255.251.0/24
    mlag_peer_l3_ipv4_pool: 10.255.250.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    spanning_tree_mode: none
  node_groups:
    DC1_LEAF34:
      bgp_as: 65201
      nodes:
        eos11:
          id: 1
          mgmt_ip: 192.168.0.20/24
          # Interface configured on SPINES to connect to this leaf
          uplink_switch_interfaces: [ Ethernet3 ]
